---
title: "Pregnanacy_Associated_Mortality_2019"
author: "emmanuella_sainvilus"
date: "2024-02-26"
output: word_document
---

```{r}
rm(list=ls())
gc()

directory <- "C:/Users/emma1/OneDrive/NYC_Open_Project"
setwd(directory)

set.seed(5289)

# Load Packages
library(readxl)
library(ggplot2)
```
```{r}
data <- read_xlsx("C:/Users/emma1/OneDrive/NYC_Open_Project/Pregnancy-Associated_Mortality_2019.xlsx")

data <- data.frame(data)

```

```{r}
summary(data$Deaths)
```
```{r}
Race.ethnicity <- c(12, 20, 6, 12, 4, 6, 9, 13)
Race.ethnicity <- as.numeric(Race.ethnicity)
summary(Race.ethnicity)
```
```{r}
Boroughs <- c(6, 9, 13, 8, 13, , 13)
Boroughs <- as.numeric(Boroughs)
summary(Boroughs)
```


```{r}
 ggplot(data, aes(x = Boroughs, y = Deaths)) +
  geom_bar(stat = "identity", fill = "skyblue") + labs(title = "Maternal Mortality Rates by Borough Year 2019")
```
```{r}
 ggplot(data, aes(x = Deaths, y = Underlying_cause)) +
  geom_bar(stat = "identity", fill = "skyblue") + labs(title = "MMR by Underlying Cause 2019")
```

```{r}
 ggplot(data, aes(x = Deaths, y = Race.ethnicity)) +
  geom_bar(stat = "identity", fill = "skyblue") + labs(title = "Maternal Mortality Rates by Race/Ethnicity Year 2019")
```


```{r}
ggplot(data, aes(x = Deaths, y = Related)) +
  geom_bar(stat = "identity", fill = "skyblue") + labs(title = "Maternal Mortality Rates Pregnancy Related Year 2019")
```

```{r}

```

```