---
title: "Pregnancy_Associated_Mortality_2016"
author: "emmanuella_sainvilus"
date: "2024-02-27"
output: word_document
---

```{r}
rm(list=ls())
gc()

directory <- "C:/Users/emma1/OneDrive/NYC_Open_Project"
setwd(directory)

set.seed(8654)

# Load Packages
library(readxl)
library(ggplot2)
```
```{r}
data <- read_xlsx("C:/Users/emma1/OneDrive/NYC_Open_Project/Pregnancy-Associated_Mortality_2016.xlsx")

data <- data.frame(data)
```

```{r}
summary(data$Deaths)
```

```{r}
Race.ethnicity <- c(4, 15, 9, 9, 8, 1, 6, 6, 2)
Race.ethnicity <- as.numeric(Race.ethnicity)
summary(Race.ethnicity)
```
```{r}
Boroughs <- c(1, 5, 4, 0, 3, 2, 5, 12, 4, 8, 4, 3)
Boroughs <- as.numeric(Boroughs)
summary(Boroughs)
```
```{r}
ggplot(data, aes(x = Deaths, y = Borough)) +
  geom_bar(stat = "identity", fill = "skyblue") + labs(title = "Maternal Mortality Rates by Borough Year 2016")
```

```{r}
ggplot(data, aes(x = Deaths, y = Race.ethnicity)) +
  geom_bar(stat = "identity", fill = "skyblue") + labs(title = "MMR's Race/Ethnicity Year 2016")
```
```{r}
ggplot(data, aes(x = Deaths, y = Underlying_cause)) +
  geom_bar(stat = "identity", fill = "skyblue") + labs(title = "MMR's by Underlying Cause Year 2016")
```

```{r}
ggplot(data, aes(x = Deaths, y = Related)) +
  geom_bar(stat = "identity", fill = "skyblue") + labs(title = "Maternal Mortality Rates by Preganancy Year 2016")
```


