---
title: "Pregnancy_Associated_Mortality_2018"
author: "emmanuella_sainvilus"
date: "2024-02-28"
output: word_document
---

```{r}
rm(list=ls())
gc()

directory <- "C:/Users/emma1/OneDrive/NYC_Open_Project"
setwd(directory)


set.seed(5824)

library(readxl)
library(ggplot2)
```

```{r}
data <- read_xlsx("C:/Users/emma1/OneDrive/NYC_Open_Project/Pregnancy-Associated_Mortality_2018.xlsx")

data <- data.frame(data)
```

```{r}
summary(data$Deaths)
```

```{r}
Boroughs <- c(10, 14, 3, 8, 2, 5, 5, 10, 1, 4, 3, 0)
Boroughs <- as.numeric(Boroughs)
summary(Boroughs)
```
```{r}
Race.ethnicity <- c(5, 20, 7, 10, 5, 2, 13, 3)
Race.ethnicity <- as.numeric(Race.ethnicity)
summary(Race.ethnicity)
```
```{r}
ggplot(data, aes(x = Deaths, y = Race.ethnicity)) +
  geom_bar(stat = "identity", fill = "skyblue", position = position_dodge(width = c(0.9, 0.7, 0.7, 0.7, 0.7, 0.7))) + labs(title = "Maternal Mortality Rates by Race/Ethinicity Year 2018")
```
```{r}
ggplot(data, aes(x = Deaths, y = Boroughs)) +
  geom_bar(stat = "identity", fill = "skyblue", position = position_dodge(width = c(0.9, 0.7, 0.7, 0.7, 0.7, 0.7))) + labs(title = "Maternal Mortality Rates by Borough Year 2018")
```
```{r}
ggplot(data, aes(x = Deaths, y = Underlying_cause)) +
  geom_bar(stat = "identity", fill = "skyblue", position = position_dodge(width = c(0.9, 0.7, 0.7, 0.7, 0.7, 0.7))) + labs(title = "Maternal Mortality Rates by Cause Year 2018")
```
```{r}
ggplot(data, aes(x = Deaths, y = Related)) +
  geom_bar(stat = "identity", fill = "skyblue", position = position_dodge(width = c(0.9, 0.7, 0.7, 0.7, 0.7, 0.7))) + labs(title = "Maternal Mortality Rates by Related Year 2018")
```

